apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ais
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - spark/spark-serviceaccount.yaml
  - spark/spark-rbac.yaml
  - visualization-api/visualization-api-deployment.yaml
  - visualization-api/visualization-api-service.yaml
  - ui/ais-ui-deployment.yaml
  - ui/ais-ui-service.yaml
  - checks/visualization-serving-check-job.yaml
