apiVersion: v1
kind: Service
metadata:
  name: ais-ui
  namespace: ais
  labels:
    app.kubernetes.io/name: ais-ui
    app.kubernetes.io/part-of: atmospheric-intelligence-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ais-ui
  ports:
    - name: http
      port: 80
      targetPort: http
